kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Clear, individual patches prevent parsing overlaps
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # Must be https and must match `issuer` in dex-config.yaml exactly.
        oidc-issuer-url: "https://kind-control-plane:32000"
        oidc-client-id: "kubernetes"
        oidc-username-claim: "email"
        oidc-groups-claim: "groups"
        oidc-ca-file: "/etc/kubernetes/dex/ca.crt"
      extraVolumes:
      - name: dex-ca
        hostPath: /etc/kubernetes/dex/ca.crt
        mountPath: /etc/kubernetes/dex/ca.crt
        readOnly: true
        pathType: File


  # oidx-issuer-url -- where Dex is hosted in
  # oidc-username-claim -- when human logs in, look at email address to see who they are -- configured in dex-config.yaml
  # oidc-groups-claim -- when human logs in, looks at groups to see what permissions they have -- configured in dex-config.yaml
  # oidc-ca-file -- public cert for Dex

  # Dex cert, generated by dex-tls/gen-certs.sh. Relative to where `kind` runs,
  # we create a homemade certfile outside of cluster, on the local machine
  # extraMounts copies that cert file into the cluster
  # extraVolumes move that cert file from the Kind node, into the API server
  # oidc-ca-file tells API server to trust Dex

  extraMounts:
  - hostPath: ./dex-tls/ca.crt
    containerPath: /etc/kubernetes/dex/ca.crt
    readOnly: true
  extraPortMappings:
  # Dex NodePort, so kubelogin on the Mac can reach the issuer.
  - containerPort: 32000
    hostPort: 32000
    protocol: TCP

  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  
  # for GatewayAPI, so we can run ingress + Gateway at the same time for testing
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
    
- role: worker
- role: worker
