apiVersion: v1
kind: ConfigMap
metadata:
  name: platform
  namespace: platform
data:
  # property-like keys; each key maps to a simple value
  backend_url: "http://user-backend:8000"
  data_file: "special_users.csv"
  sleep_duration: "10"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-a
  namespace: client-a
data:
  # property-like keys; each key maps to a simple value
  # user-backend lives in the platform namespace, so the short name won't resolve from here
  backend_url: "http://user-backend.platform.svc.cluster.local:8000"
